namespace PreferredElementData.Models
{
    public class ItemBrick
    {
        public int ItemId { get; set; }
        public int BrickId { get; set; }
        public int Amount { get; set; }
        public DateTime Created { get; set; }

        public Item Item { get; set; }
        public Brick Brick { get; set; }
    }

    // Considerations:
    // Logically, we need to be able to store how many of a given brick
    // is in a given set. Otherwise, this table could have been
    // autogenerated by EF without us having to define it in code.
}
